add_executable(kshell_parser_tests parser_tests.cpp)
target_link_libraries(kshell_parser_tests PRIVATE kshell_core)
if(NOT MSVC)
    target_link_options(kshell_parser_tests PRIVATE -static)
endif()
add_test(NAME ParserTests COMMAND kshell_parser_tests)

add_executable(kshell_history_tests history_tests.cpp)
target_link_libraries(kshell_history_tests PRIVATE kshell_core)
if(NOT MSVC)
    target_link_options(kshell_history_tests PRIVATE -static)
endif()
add_test(NAME HistoryTests COMMAND kshell_history_tests)

add_executable(kshell_command_tests command_tests.cpp)
target_link_libraries(kshell_command_tests PRIVATE kshell_core)
if(NOT MSVC)
    target_link_options(kshell_command_tests PRIVATE -static)
endif()
add_test(NAME CommandTests COMMAND kshell_command_tests)

add_executable(kshell_tui_tests tui_tests.cpp)
target_link_libraries(kshell_tui_tests PRIVATE kshell_core)
if(NOT MSVC)
    target_link_options(kshell_tui_tests PRIVATE -static)
endif()
add_test(NAME TUITests COMMAND kshell_tui_tests)
